import { useState, useEffect } from "react";
import Head from "next/head";
import { motion } from "framer-motion";
import { getCategories } from "~/utils/axios.instance";
import LoadingScreen from "~/components/LoadingScreen/LoadingScreen";
import Hero from "~/components/Hero/Hero";
import MealCard from "~/components/MealCard/MealCard";

export default function Home() {
  const [categories, setCategories] = useState();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function getData() {
      await getCategories().then((response) => {
        setCategories(response.data.categories);
      });
      setLoading(false);
    }

    getData();
  }, [categories]);

  if (loading) {
    return <LoadingScreen />;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.8 }}
      >
        <Hero />
        <div className="mx-auto grid max-w-screen-lg grid-cols-2 gap-5 p-10 md:grid-cols-3 md:px-0 lg:grid-cols-5">
          {categories?.map((category) => (
            <MealCard
              key={category.idCategory}
              category={category.strCategory}
              thumbnail={category.strCategoryThumb}
              nextLink="category"
              params={category.strCategory}
            />
          ))}
        </div>
      </motion.main>
    </div>
  );
}
